<%@ Page Title="All Vendor Costing" Language="C#" MasterPageFile="~/BDM/BDM.Master" AutoEventWireup="true" CodeBehind="AllVendorCosting.aspx.cs" Inherits="Vendor_Portal.BDM.AllVendorCosting" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <script src="../Scripts/Functions/AllVendorCosting.js?v=3"></script>
    <style>
        #avc_loading{display:none;position:fixed;inset:0;z-index:99999;background:rgba(255,255,255,.78);text-align:center;padding-top:260px;font-weight:bold}.avc-filter{border:1px solid #dce3eb;border-radius:6px;background:#f8fafc;padding:18px 18px 8px;margin-bottom:14px}.avc-filter-title{font-size:15px;font-weight:700;color:#26374a;margin:0 0 13px}.avc-control{display:none}.avc-filter label{display:block;font-size:12px;font-weight:600;color:#334155;margin-bottom:5px}.avc-filter .form-control{height:36px;font-size:13px}.avc-label{font-weight:600;color:#334155;margin:.25rem 0 .75rem}#avc_periodB{display:none;border-top:1px solid #dce3eb;margin-top:5px;padding-top:15px}#avc_summary th,#avc_summary td,#avc_detail th,#avc_detail td{box-sizing:border-box;white-space:nowrap}#avc_summary thead th,#avc_detail thead th{white-space:normal;overflow-wrap:anywhere;text-align:center;vertical-align:middle;background:linear-gradient(to bottom,#cbd0dd 3%,#fff)!important;color:#000}#avc_summary tfoot th,#avc_detail tfoot th{vertical-align:middle}#avc_summary tr.avc-missing td,#avc_detail tr.avc-missing td{background:#f8d7da!important;color:#842029;font-weight:600}#avc_message{display:none}#avc_invoiceModal{overflow:hidden}#avc_invoiceModal .modal-dialog{height:calc(100vh - 2rem);margin:1rem auto}#avc_invoiceModal .modal-content{height:100%;overflow:hidden}#avc_invoiceModal .modal-body{min-height:0;overflow:hidden}#avc_invoiceModal .table-responsive{height:100%;overflow:hidden}#avc_invoiceModal .dataTables_wrapper{height:100%}#avc_invoiceModal .dataTables_scrollBody{overflow:auto!important}div.dt-buttons{float:left;margin-right:1rem}@media(max-width:767px){.avc-filter{padding:14px 14px 5px}.avc-search-wrap{text-align:left!important}}
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div id="avc_loading" aria-live="polite"><img src="../images/Load_1.gif" alt="Loading" /><br />Loading, please wait...</div>
    <div class="content-header"><div class="container"><div class="row mb-2 callout callout-info"><div class="col-sm-6"><h6 class="m-0"><i class="fas fa-copy"></i>&nbsp;&nbsp;<b>All Vendor Costing</b></h6></div></div></div></div>
    <div class="col-lg-12"><div class="card"><div class="card-body">
        <div class="avc-filter"><div class="avc-filter-title">Report Filters</div><div class="row align-items-end">
            <div class="col-lg-3 col-md-6 form-group"><label for="avc_aType">Period Type</label><select id="avc_aType" class="form-control avc-type"><option value="month">Month-Year</option><option value="ytd">YTD</option><option value="quarter">Quarterly</option></select></div>
            <div class="avc-control col-lg-4 col-md-6 form-group" data-period="a" data-type="month"><label for="avc_aMonth">Month</label><select id="avc_aMonth" class="form-control avc-month"></select></div><div class="avc-control col-lg-2 col-md-4 form-group" data-period="a" data-type="month"><label for="avc_aMonthYear">Year</label><select id="avc_aMonthYear" class="form-control avc-year"></select></div>
            <div class="avc-control col-lg-4 col-md-6 form-group" data-period="a" data-type="quarter"><label for="avc_aQuarter">Quarter</label><select id="avc_aQuarter" class="form-control"><option value="1">Q1 (Jan-Mar)</option><option value="2">Q2 (Apr-Jun)</option><option value="3">Q3 (Jul-Sep)</option><option value="4">Q4 (Oct-Dec)</option></select></div><div class="avc-control col-lg-2 col-md-4 form-group" data-period="a" data-type="quarter"><label for="avc_aQuarterYear">Year</label><select id="avc_aQuarterYear" class="form-control avc-year"></select></div>
            <div class="avc-control col-lg-4 col-md-6 form-group" data-period="a" data-type="ytd"><label for="avc_aYtdMonth">Through Month</label><select id="avc_aYtdMonth" class="form-control avc-month"></select></div><div class="avc-control col-lg-2 col-md-4 form-group" data-period="a" data-type="ytd"><label for="avc_aYtdYear">Year</label><select id="avc_aYtdYear" class="form-control avc-year"></select></div>
            <div class="col-lg-3 col-md-6 form-group"><label for="avc_comparison">Compare With (Optional)</label><select id="avc_comparison" class="form-control"><option value="none">Do Not Compare</option><option value="previous">Previous Period</option><option value="previousYear">Previous Year</option><option value="manual">Select Another Period</option></select></div>
        </div><div id="avc_periodB"><div class="avc-filter-title">Comparison Period</div><div class="row align-items-end">
            <div class="col-lg-3 col-md-6 form-group"><label for="avc_bType">Period Type</label><select id="avc_bType" class="form-control avc-type"><option value="month">Month-Year</option><option value="ytd">YTD</option><option value="quarter">Quarterly</option></select></div>
            <div class="avc-control col-lg-4 col-md-6 form-group" data-period="b" data-type="month"><label for="avc_bMonth">Month</label><select id="avc_bMonth" class="form-control avc-month"></select></div><div class="avc-control col-lg-2 col-md-4 form-group" data-period="b" data-type="month"><label for="avc_bMonthYear">Year</label><select id="avc_bMonthYear" class="form-control avc-year"></select></div>
            <div class="avc-control col-lg-4 col-md-6 form-group" data-period="b" data-type="quarter"><label for="avc_bQuarter">Quarter</label><select id="avc_bQuarter" class="form-control"><option value="1">Q1 (Jan-Mar)</option><option value="2">Q2 (Apr-Jun)</option><option value="3">Q3 (Jul-Sep)</option><option value="4">Q4 (Oct-Dec)</option></select></div><div class="avc-control col-lg-2 col-md-4 form-group" data-period="b" data-type="quarter"><label for="avc_bQuarterYear">Year</label><select id="avc_bQuarterYear" class="form-control avc-year"></select></div>
            <div class="avc-control col-lg-4 col-md-6 form-group" data-period="b" data-type="ytd"><label for="avc_bYtdMonth">Through Month</label><select id="avc_bYtdMonth" class="form-control avc-month"></select></div><div class="avc-control col-lg-2 col-md-4 form-group" data-period="b" data-type="ytd"><label for="avc_bYtdYear">Year</label><select id="avc_bYtdYear" class="form-control avc-year"></select></div>
        </div></div></div>
        <div class="row align-items-center"><div class="col-md-9"><div id="avc_periodALabel" class="avc-label"></div><div id="avc_periodBLabel" class="avc-label"></div></div><div class="col-md-3 form-group text-right avc-search-wrap"><button type="button" id="avc_search" class="btn btn-primary px-4"><i class="fas fa-search"></i>&nbsp; Generate Report</button></div></div>
        <div id="avc_message" class="alert" role="alert"></div>
        <ul class="nav nav-tabs" role="tablist"><li class="nav-item"><a class="nav-link active" data-toggle="pill" href="#avc_detailPane" role="tab"><b>Project-wise Report</b></a></li><li class="nav-item"><a class="nav-link" data-toggle="pill" href="#avc_summaryPane" role="tab"><b>Management Summary</b></a></li></ul>
        <div class="tab-content pt-3"><div id="avc_detailPane" class="tab-pane fade show active" role="tabpanel"><table id="avc_detail" class="table table-bordered table-striped" style="width:100%"></table></div><div id="avc_summaryPane" class="tab-pane fade" role="tabpanel"><table id="avc_summary" class="table table-bordered table-striped" style="width:100%"></table></div></div>
    </div></div></div>
    <div class="modal fade" id="avc_invoiceModal" tabindex="-1" role="dialog"><div class="modal-dialog modal-xl" role="document"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="avc_invoiceTitle">Invoice Details</h5><button type="button" class="close" data-dismiss="modal">&times;</button></div><div class="modal-body"><div class="table-responsive"><table id="avc_invoiceTable" class="table table-bordered table-striped" style="width:100%"></table></div></div></div></div></div>
</asp:Content>
