//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vendor_Portal.BDM
{
    public partial class AllVendorCosting
    {
    }
}
